travis:
  secure:
    BINSTAR_TOKEN: SjjJWYn44jrQU3mHPVo05KnuGRcZ5aT8mXcfbMxtFI5LVY3S+BFhVODi2i6cwVzZDnGAWf+l0Hsr6Lr6jqTGqDTTeLGyKPYnVtaIYEbptgCENasf0JToiCRk51oiw+EKXs+tRdtHnwgEmICEVRIk7YguzFvdcBwde7SBI/5z3LjSkr4Efw1MZ3nFeMxsejXBsTnd3ExIdw4GLAytntKMSAx9Xsnno/3KIhDqIUTFcbJO6Q/+kKL4mbGlI5MTeM9SSnm3vvd/8srivv1P4H9rV9xguq/koNQS6r9aJ1uFKqMvsYiXjJS4NPb2wrc1gUpgF8X+wSCKcnNknYbw0LNLmCC2HlDFCXqHj2roa6+8tRo6UOBNhPvfuTqbYtmaEB6igZPNacooqIxCZ9gOnxDTWOoacHWItUrIz1+RWwVbGn4QJqQbqsn1H6tGU2jI2EYnNZXoQHVWK6k8RaYmUEBAItMDCqSELSQH+3WBrmjF6D8BebEIkClAKV+eGAgqHQw45B88iR0Ew3RqMlwxUt8LW2gr6A9pfwzVO9/i+Jy9ir0Zh4Bd2yQ8+yCVw9hKN9hYrnRfhFetNejasWhFnZgnlW30rYk4EksNvktz3xXLkXa8qj9l4QdjxsHuceXD0uWrqJv/LPRgs4KPAHsgZMV0JWXNWi280/TfD3uwGlooLH0=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
